### ISSUE TITLE
Update Words.md

### ISSUE THREAD

**Issue by malakar-soham** [malakar-soham/ez#11]
**Task**<br>
Increase the number of words

**Description**
- Introduce at least 30 new entries currently it's just 6

**Branch**<br>
PR in `docs` branch

**Comment by rexdivakar** [comment]
Assign it on my name @malakar-soham  i will work on it

**Comment by malakar-soham** [comment]
Let this be an issue open for all, I'll merge the one which comes the earliest with the proper format and definitions 👍
