### ISSUE TITLE
Change the navbar

### ISSUE THREAD

**Issue by malakar-soham** [malakar-soham/ez#30]
**Task**
The frontend navbar needs to be changed from the `web` branch

**Description**
- Take a look at `design` branch to know how the webpage should look
- Change the nav bar

**Branch**
PR to `web` branch

**Comment by DeepakR-28** [comment]
I would like to work on it Soham.

**Comment by malakar-soham** [comment]
@DeepakR-28 how far have you progressed with this issue?

**Comment by malakar-soham** [comment]
This issue is open to anyone willing to contribute
