### ISSUE TITLE
Slang Page

### ISSUE THREAD

**Issue by malakar-soham** [malakar-soham/ez#33]
**Task**<br>
Design the slang page

**Description**
- Check for designs in `design` branch
- Create the design for the slang page with the same feel as the other pages

**Branch**<br>
PR in `design` branch

**Comment by tory-brown** [comment]
i would like to take this on

**Comment by malakar-soham** [comment]
You can check the `homepage` from the `design` folder to get a feel of the page and make it consistent. Good Luck 👍
