### ISSUE TITLE
Add a banner to ReadMe

### ISSUE THREAD

**Issue by malakar-soham** [malakar-soham/ez#40]
**Task**<br>
Add a banner to ReadMe in `design` branch

**Description**
- Remove the heading `Esports Zealot`
- Add a banner of 1400x500 px with the logo and the name  

**Branch**<br>
PR in `design` branch

**Comment by ebeohp** [comment]
I'm interested in this

**Comment by malakar-soham** [comment]
@ebeohp you can find the logo in `design` branch in `Design` folder.
As per how it should look, go wild with your imagination but keep these words in mind - gaming, streaming. For more ideas you can discuss in our [Discord](https://discord.gg/42pvfZ2) server
Good luck 👍

**Comment by ebeohp** [comment]
Cool! I'll let you know if I have any more questions. :)
