### ISSUE TITLE
Front end for the website

### ISSUE THREAD

**Issue by malakar-soham** [malakar-soham/ez#42]
**Task**<br>
Make the remaining front end of the website

**Description**
- Check the `design` branch to get a feel of how the homepage should look
- Make a similar front end, using the resources of `web` branch
 OR
Make a similar front end, using any framework you are comfortable with

**Branch**<br>
PR in `web` branch

**Comment by fletcherrippon** [comment]
Is this just creating the home page or other pages?

**Comment by malakar-soham** [comment]
Just the homepage, we will be adding issues for subsequent pages

**Comment by fletcherrippon** [comment]
Can I be assigned this issue?

**Comment by malakar-soham** [comment]
Okay, I'm assigning you. For more ideas you can discuss in our [Discord](https://discord.gg/42pvfZ2) server. 
Good Luck 👍

**Comment by fletcherrippon** [comment]
Ok thanks 😄
