### ISSUE TITLE
Front end

### ISSUE THREAD

**Issue by malakar-soham** [malakar-soham/ez#5]
**Task**
The structure of the website needs to be created

**Description**
- Creating base structure
- Depend on #2 or could build a base structure and edit that later

**Branch**
PR in `web` branch

**Comment by KaranSinghBisht** [comment]
Hey I am using react is that fine?
I am creating a basic navbar that is mobile compatible

**Comment by malakar-soham** [comment]
Yeah sure but I would suggest you to wait for the resolution of issue #2 before taking up this issue, in order to know what all to put in the navbar. In the meantime you could join our [Discord](https://discord.gg/42pvfZ2) server and take part in the discussion

**Comment by malakar-soham** [comment]
Use any framework you prefer
