### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by malakar-soham** [malakar-soham/ez#53]
**Task**<br>
Design the `about` page

**Description**
- Check for designs in design branch
- Create the design for the about page with the same feel as the other pages

**Branch**<br>
PR in `design` branch

**Comment by EANimesha** [comment]
I will do this. Assign me

**Comment by tory-brown** [comment]
Has this been assigned to anyone yet

**Comment by malakar-soham** [comment]
@EANimesha and @tory-brown also check out issue #33 , it's related to designing. Let us know in the comments or in our [Discord](https://discord.gg/42pvfZ2) server which one you want to work and we will assign likewise

**Comment by malakar-soham** [comment]
@EANimesha I'm assigning this to you
