### ISSUE TITLE
Database required

### ISSUE THREAD

**Issue by malakar-soham** [malakar-soham/ez#6]
**Task**<br>
Database needs to be added and populated with the entries in `words.md` file in `docs` branch

**Description**
- A sqlite file needs to be added
- Set the file name to `wordbase`
- Set the `primary key` to be *slang* , check [Format](https://github.com/malakar-soham/ez#format)

**Branch**<br>
PR in `web` branch

**Comment by rexdivakar** [comment]
Assign it to me i can work on it @malakar-soham

**Comment by rexdivakar** [comment]
Do u want me to add it manually to the database file or do u want me to script it to parse the data ? @malakar-soham

**Comment by malakar-soham** [comment]
Since it will be a read-only db, used for the searching the words on a static webpage, you could script it to parse the data from the `Words.md` file in `docs` branch and also add that script for future use. But remember it's a static webpage

**Comment by malakar-soham** [comment]
@rexdivakar how far have you progressed with this issue?

**Comment by rexdivakar** [comment]
Will raise a PR tomorrow.

**Comment by malakar-soham** [comment]
Cool
